version: "3.9"

services:
#  ollama:
#    image: ollama/ollama
#    container_name: ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama:/root/.ollama

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
#      - OLLAMA_BASE_URL=http://ollama:11434
#    depends_on:
#      - ollama
    volumes:
      - ./backend/app:/app/app
      - ./backend/chroma_db:/app/chroma_db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend

#volumes:
#  ollama:
